"""The list of channels you actually want.

This is the single most important input for a large provider. Without it,
verification means probing every candidate for all 55,000 listed streams,
which is not a long job -- it is an impossible one. With it, probarr probes
only candidates for the couple of hundred channels you care about.

Format is deliberately the plainest thing that works, so it can be written by
hand, generated by a script, or pasted from a channel-lineup web page:

    # comments and blank lines ignored
    101: BBC One
    102: BBC Two
    BBC Four            <- number optional
    401: Meridian Sports Main Event | meridian.main.uk    <- optional tvg-id after |

    [Meridian Sports]                                  <- optional group header
    407: Meridian Sports 1
    408: Meridian Sports Golf

Numbering is preserved so an exported playlist can carry real channel numbers
rather than the order things happened to be probed in.

A `[Group Name]` line on its own sets the group for every channel line that
follows, until the next header (or end of file). This exists so Curate's
Groups view doesn't have to be rebuilt by hand on every new run of the same
lineup: a channel's group is a durable per-channel decision already carried
forward for an *existing* lineup (see lineups.py), but that inheritance has
nothing to inherit FROM on a lineup's very first run -- a header in the
wantlist itself seeds it from the start. It only ever seeds; a group set
afterwards in Curate always wins over what the wantlist says on the next run.
An empty `[]` resets to no group, for channels between two named sections
that don't belong in either.
"""
import os
import re

TEMPLATE = """# probarr wantlist
#
# One channel per line. These are the channels you WANT -- probarr only probes
# candidate streams for these, which is the difference between a run that takes
# twenty minutes and one that never finishes.
#
# Format (everything except the name is optional):
#
#   <number>: <name> | <tvg-id>
#
#   101: BBC One                                name with a channel number
#   BBC Four                                    name only
#   401: Meridian Sports Main Event | meridian.main.uk    with an explicit EPG id
#
# The number is carried through to exported playlists, so your lineup keeps
# real channel numbers rather than the order things happened to be probed in.
# The tvg-id is only needed when a channel's guide listing cannot be found by
# name.
#
# Lines starting with # are ignored, as are blank lines.
#
# A [Group Name] line on its own sets the group for the channels that follow
# it, until the next one -- so Curate's Groups view starts already organised
# instead of being rebuilt by hand after every new lineup's first run.
#
# Names are matched loosely: case, punctuation and quality tags such as
# HD/FHD/UHD/4K are ignored, so "BBC One" will match a stream listed as
# "UKFHD | BBC One HD".
#
# Replace the examples below with your own channels.

[Entertainment]
101: BBC One
102: BBC Two
103: BBC Three
104: BBC Four
105: BBC Parliament
120: CBBC
121: CBeebies
130: S4C

[News & Business]
140: Bloomberg TV
"""


def safe_name(name):
    """Filesystem-safe wantlist name. None if nothing usable remains.

    Names arrive from the browser and become filenames, so this is a security
    boundary, not tidiness: anything outside the allowed set is replaced rather
    than stripped, so "../../etc/passwd" cannot survive as a path.
    """
    cleaned = re.sub(r"[^A-Za-z0-9._-]", "-", (name or "").strip())[:64]
    cleaned = cleaned.strip("-.")
    return cleaned or None


def store_dir(root):
    d = os.path.join(root, "wantlists")
    os.makedirs(d, exist_ok=True)
    return d


def list_saved(root):
    d = store_dir(root)
    out = []
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".txt"):
            continue
        path = os.path.join(d, fn)
        try:
            st = os.stat(path)
            with open(path, encoding="utf-8", errors="replace") as f:
                lines = sum(1 for line in f
                            if line.strip() and not line.strip().startswith("#"))
        except OSError:
            continue
        out.append({"name": fn[:-4], "channels": lines,
                    "bytes": st.st_size, "modified": st.st_mtime})
    return out


def read_saved(root, name):
    n = safe_name(name)
    if not n:
        return None
    path = os.path.join(store_dir(root), n + ".txt")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read()


def write_saved(root, name, text):
    n = safe_name(name)
    if not n:
        raise ValueError("invalid wantlist name")
    path = os.path.join(store_dir(root), n + ".txt")
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, path)
    return n


def delete_saved(root, name):
    n = safe_name(name)
    if not n:
        return False
    path = os.path.join(store_dir(root), n + ".txt")
    if os.path.exists(path):
        os.remove(path)
        return True
    return False


def resolve_path(root, spec):
    """Accept either a filesystem path or the name of a saved wantlist.

    Lets --wantlist take 'my-lineup' as well as '/config/wantlists/my-lineup.txt',
    so a list created in the UI can be used from the CLI without the operator
    having to know where it was filed.
    """
    if os.path.exists(spec):
        return spec
    name = safe_name(spec)
    if name:
        candidate = os.path.join(store_dir(root), name + ".txt")
        if os.path.exists(candidate):
            return candidate
    return spec

_LINE_RE = re.compile(r"""
    ^\s*
    (?:(?P<number>\d{1,5})\s*[:.)\-]\s*)?   # optional leading channel number
    (?P<name>[^|]+?)                        # channel name
    (?:\s*\|\s*(?P<tvg>\S+))?               # optional |tvg-id
    \s*$
""", re.X)


class WantedChannel:
    __slots__ = ("number", "name", "tvg_id", "key", "group")

    def __init__(self, number, name, tvg_id, key, group=None):
        self.number, self.name, self.tvg_id, self.key = number, name, tvg_id, key
        self.group = group

    def as_dict(self):
        return {"number": self.number, "name": self.name,
                "tvg_id": self.tvg_id, "key": self.key, "group": self.group}


_GROUP_HEADER_RE = re.compile(r"^\[(.*)\]$")


def parse_detailed(text, normalizer):
    """Parse wantlist text. Returns (channels, warnings).

    Warnings are surfaced in the UI rather than dropped. A hand-written list
    picks up duplicates and typos, and a line silently ignored is a channel the
    operator believes is being checked and is not.
    """
    out, seen, warnings = [], {}, []
    current_group = None
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        gm = _GROUP_HEADER_RE.match(line)
        if gm:
            current_group = gm.group(1).strip() or None
            continue
        m = _LINE_RE.match(line)
        if not m:
            warnings.append({"line": lineno, "text": raw.strip(),
                             "problem": "could not be parsed"})
            continue
        name = m.group("name").strip()
        if not name:
            warnings.append({"line": lineno, "text": raw.strip(),
                             "problem": "no channel name"})
            continue
        key = normalizer.key(name)
        if not key:
            warnings.append({"line": lineno, "text": raw.strip(),
                             "problem": "name normalises to nothing"})
            continue
        if key in seen:
            # A duplicate name under two different numbers is an easy slip in a
            # hand-written list, and silently keeping one of them is confusing
            # later. First occurrence wins, and the operator is told.
            warnings.append({"line": lineno, "text": raw.strip(),
                             "problem": f"duplicate of line {seen[key]}, ignored"})
            continue
        seen[key] = lineno
        out.append(WantedChannel(
            int(m.group("number")) if m.group("number") else None,
            name, m.group("tvg") or "", key, current_group))
    return out, warnings


def parse(text, normalizer):
    """Parse wantlist text into WantedChannel objects, in file order."""
    return parse_detailed(text, normalizer)[0]


def load(path, normalizer):
    with open(path, encoding="utf-8", errors="replace") as f:
        return parse(f.read(), normalizer)


MIN_FUZZY_LEN = 5

# How much extra trailing text the REVERSE case (wantlist more specific than
# the listing) will tolerate before refusing to guess. A short qualifier like
# "UK" is almost certainly noise the user added; a whole extra word is not.
# Real, demonstrated case: "Comedy Central Xtra" (key "COMEDYCENTRALXTRA")
# reverse-matched the plain "Comedy Central" pool ("COMEDYCENTRAL" is a
# prefix of it) even though this provider's catalog has no distinct Xtra
# feed at all -- "Xtra" IS the whole point of that channel name, not a
# qualifier to discard. That silently gave two different Dispatcharr
# channels the exact same underlying stream under two different EPG
# identities, with no warning visible anywhere a curator would see it.
MAX_FUZZY_SUFFIX = 3


def _fuzzy(key, pools):
    """Closest pool key when the exact one is absent.

    Real playlists qualify names in ways a hand-written wantlist will not:
    "BBC One" is listed as "BBC One London", "Meridian Sports Main Event" as
    "Meridian Sports Main Event UK". So a wanted key that is a prefix of exactly
    one family of pool keys resolves to the shortest of them -- shortest
    because it is the least qualified, and therefore the most likely to be the
    plain channel rather than a regional variant.

    Guarded by a minimum length: a three-letter wanted name is a prefix of far
    too much to guess safely.
    """
    if len(key) < MIN_FUZZY_LEN:
        return None

    # Brand prefixes the provider and the wantlist disagree about.
    #
    # UKTV rebranded its channels with a "U&" prefix (U&Alibi, U&Yesterday,
    # U&Dave) but providers apply it inconsistently -- confirmed in one real
    # catalogue where "U&Dave" and "U&GOLD" are listed WITH it while Alibi,
    # Yesterday, Drama, Eden and W are listed without. A wantlist naming
    # them the official way therefore matched some and silently missed the
    # rest. Tried in both directions since either side may carry it.
    alts = []
    if key.startswith("UAND"):
        alts.append(key[4:])
    else:
        alts.append("UAND" + key)
    for alt in alts:
        if len(alt) >= MIN_FUZZY_LEN and alt in pools:
            return alt

    hits = [k for k in pools if k.startswith(key)]
    if not hits:
        # The reverse case: wantlist more specific than the listing. Capped
        # by MAX_FUZZY_SUFFIX -- see its docstring for why an unrestricted
        # version of this is a real bug, not just theoretical over-caution.
        hits = [k for k in pools if key.startswith(k) and len(k) >= MIN_FUZZY_LEN
               and len(key) - len(k) <= MAX_FUZZY_SUFFIX]
    if not hits:
        # The provider prefixes a platform brand the wantlist omits --
        # "Disney+ Cinema" listed as "Meridian Disney+ Cinema". Only accepted
        # when exactly one pool key ends with the wanted name, so a generic
        # short name cannot sweep up a family of unrelated channels.
        hits = [k for k in pools if k.endswith(key) and k != key]
        if len(hits) != 1:
            return None
    if not hits:
        return None
    return min(hits, key=len)


def apply(wanted, pools, fuzzy=True):
    """Restrict candidate pools to wanted channels.

    Returns (filtered_pools, missing, fuzzy_matches). `missing` is the wanted
    channels with no candidate stream at all -- reported prominently, because a
    silently absent channel is indistinguishable from one that simply failed,
    and the usual cause is a name that needs an alias rather than a provider
    gap. `fuzzy_matches` is reported too: an inexact match is a guess, and a
    guess the operator cannot see is a guess they cannot correct.
    """
    filtered, missing, fuzzy_matches = {}, [], []
    for w in wanted:
        streams = pools.get(w.key)
        if streams:
            filtered[w.key] = streams
            continue
        alt = _fuzzy(w.key, pools) if fuzzy else None
        if alt:
            filtered[w.key] = pools[alt]
            fuzzy_matches.append((w, alt))
        else:
            missing.append(w)
    return filtered, missing, fuzzy_matches
